import "./globals.css";
import type { Metadata } from "next";
import SupabaseProvider from "./supabasaeProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<SupabaseProvider>{children}</SupabaseProvider>
			</body>
		</html>
	);
}
